### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by EmoMeza** [EmoMeza/proyecto-informatico#1]
Cosas por hacer:

- [x] Deploy Inicial
- [x] Conectarse a la base de datos
- [x] crear endpoints api

Endpoints API:
- [x] Añadir Evento
- [x] Editar Evento
- [x] Recibir Evento
- [x] Eliminar Evento
- [x] Recibir Todos los Eventos
- [x] Filtrar Eventos (Categoria)
- [x] Añadir Alumno
- [x] Editar Ramos Alumno
- [x] Recibir Alumno

**Comment by EmoMeza** [comment]
Más enpoints necesarios:

- [ ] Añadir Ingresos a evento
- [ ] Recibir Ingresos totales de un evento
- [ ] Añadir Egresos a evento
- [ ] Recibir Egresos totales de un evento
- [ ] Recibir el total (Ingresos - Egresos) de un evento
- [ ] Añadir alumno a un evento
- [ ] Obtener una lista de los que asistiran a un evento

**Comment by Daniel-Michel0** [comment]
- [ ] Hacer endpoints para crear cuenta e inicio de sesión
