### ISSUE TITLE
Error postIngresoEventos()

### ISSUE THREAD

**Issue by Almatamala** [EmoMeza/proyecto-informatico#10]
cambiar la linea 757 por 
id_caa = result.id_creador;

**Comment by EmoMeza** [comment]
Listo! agregado al main!

**Comment by Almatamala** [comment]
mismo problema que antes pero ahora en egresos.
A la hora de agregar egresos a un evento utilizando la función postEgresoEvento() no se crea una copia en egresos en Caa que contenga la id del evento.

sugerencia: revisar la linea 819 de app.js
