### ISSUE TITLE
error postEgresoEvento()

### ISSUE THREAD

**Issue by Almatamala** [EmoMeza/proyecto-informatico#13]
mismo problema que antes pero ahora en egresos.
A la hora de agregar egresos a un evento utilizando la función postEgresoEvento() no se crea una copia en egresos en Caa que contenga la id del evento.

sugerencia: revisar la linea 819 de app.js

**Comment by EmoMeza** [comment]
Hola!, @Almatamala 

deberia de estar arreglado, debido a que estoy con mas proyectos ahora te invito a probarlo y en caso que el error persista o aparezca una nuevo, serviría muchisimo que enviaras ademas los logs que te aparecen del error al igual que el id_evento que estas utilizando y el id del caa relacionado, es decir el test que estas haciendo que no te funciona.

**Comment by EmoMeza** [comment]
Los cambios se encuentran en el main. Cuentame como resulta todo, saludos!

**Comment by Almatamala** [comment]
La funcion se queda en estado "seding request", el cambio es efectuado en caa pero traba la applicacion ya que la api no retorna request

**Comment by EmoMeza** [comment]
Hola! @Almatamala , 

no he podido testear ya que estoy con otro proyecto, pero arreglé lo que me mencionaste asi que deberia de retornar que fue agregado exitosamente. Cualquier problema que surga me dices.

Si para mañana no hay ningun problema cerraré el issue, mientras tanto lo dejaré abierto.

(Recordar que los cambios se realizan en la branch "main", asi que para verlos reflejados en tu rama es neceario hacer merge)

Saludos!

**Comment by Almatamala** [comment]
El problema es que ApiResponse no retorna nada y la aplicacion no sigue hasta que retorna el error de tiempo

**Comment by EmoMeza** [comment]
En ese caso me parece extraño, podrías mostrarme bien el error, adjuntando el mensaje de error, que endpoint estas usando, que estas entregando, etc...

Gracias!

**Comment by Almatamala** [comment]
mientras te mandaba el error que salía en postman note que ahora funciona correctamente, ni idea como pero esperemos que siga así.

gracias por tu tiempo
