### ISSUE TITLE
Cambio en subir imagen que lo reciba como parte del body

### ISSUE THREAD

**Issue by mvillarios** [EmoMeza/proyecto-informatico#15]
- [ ] Dejar la conversión de la imagen al frontend debido a problemas al mandar el archivo.

Hay problemas para mandar archivos al backend desde el front, entonces es mejor que se haga la conversion de la imagen en el front y que la api la reciba dentro del body

**Comment by EmoMeza** [comment]
Holis @mvillarios , recién tengo tiempo, ahora lo voy a hacer. 

En ese caso espero a que manden en el body el string de la imagen en abse 64. Te aviso apenas lo incluya.

Saludos!

**Comment by EmoMeza** [comment]
Por lo que entendí que se necesita deberia estar actualizado en el backend que se encuentra en el branch main. Si se encuentran algun problema me lo dicen, pero mientras lo entreguen en el body del json con base64 no deberia haber drama.

Igualmente necesito que me expliquen bien si quieren agregar una imagen a ingresos/egresos, tanto para caa como para un evento. Debido a que eso toma mas tiempo y necesito saber bien que es lo que se quiere. 

Ejemplo:

Se quiere que se pueda subir siempre una imagen con un ingreso, o que se pueda elegir, etc...

Creo haber escuchado que el que queria esto era @Almatamala, pero si no es algo 100% necesario igualmente recomiendo no implementarlo por temas de tiempo. No sé las opiniones de @dimaldonado @Daniel-Michel0 @mvillarios 

Saludos!

**Comment by mvillarios** [comment]
Perfecto ahora se podrá terminar lo que faltaba en el front.

Con respecto a lo de las imágenes en los ingresos y egresos la idea era que los usuarios pudieran subir cosas como boletas o cualquier cosa que justifique el ingreso o egreso, pero si crees que es mucho trabajo lo dejamos así, porque igual queda poco tiempo para la entrega

**Comment by EmoMeza** [comment]
Okis! voy a cerrar este issue en ese caso, si presentan algun problema abranlo de nuevo uwu

**Comment by carlops22** [comment]
Se puede aumentar el tamaño máximo? @EmoMeza  


Cuando intento enviar una imagen en base64
![image](https://github.com/EmoMeza/proyecto-informatico/assets/28035663/5eae64ac-b9e1-41f4-be0a-81e2b2772ece)
Al parecer hay un máximo que puede recibir el server (no sé cuanto es exactamente),  midiendo desde el frontend por ejemplo: la imagen comprimida y encodeada en base64:
![image](https://github.com/EmoMeza/proyecto-informatico/assets/28035663/12ed8e9e-2df9-4511-9e06-b1fc5b89e4f2)

Sin embargo pude postear 2 eventos con imagenes encodeadas menores a 100 kb sin ningun problema:
![image](https://github.com/EmoMeza/proyecto-informatico/assets/28035663/82e9fef2-6a1b-42e9-9b62-997f9f9af5f8)

**Comment by EmoMeza** [comment]
@carlops22 No tengo una buena forma de testearlo ahora ya que no sé como estan manejando las cosas desde el front. Estuve leyendo y resulta que por default nodejs y express especificamente connect(), setea automaticamente el limite a 1mb, revisando un poco y buscando, encontré como solucionarlo en teoria.

Testea a ver si te deja, el nuevo límite esta en 50mb. Cualquier cosa me dices.

**Comment by carlops22** [comment]
Probado y funciona de maravilla. Gracias ^^ , cerraré el issue.
