### ISSUE TITLE
Error al agregar notificaciones para eventos

### ISSUE THREAD

**Issue by Daniel-Michel0** [EmoMeza/proyecto-informatico#16]
Desde la vista de alumno, al añadir una notificación para un evento se genera el siguiente error:

![image](https://github.com/EmoMeza/proyecto-informatico/assets/69818880/618524a2-5539-4a94-9edc-46c1106dc65c)

Se da el error con horas, días y semanas.

Se probó en un emulador android.

**Comment by mvillarios** [comment]
Buenas noches compañero @Daniel-Michel0, he revisado el error que me enviaste y lo he solucionado.
El origen del problema fue que se necesitaban agregar permisos al AndroidManifest para que funcionara.
Espero que estes bien. ¡Saludos!
