### ISSUE TITLE
Error al filtrar eventos en menuAlumno

### ISSUE THREAD

**Issue by Daniel-Michel0** [EmoMeza/proyecto-informatico#17]
Al filtrar eventos que empiecen el mismo día que se filtra, este no se muestra.
Ejemplo:

![image](https://github.com/EmoMeza/proyecto-informatico/assets/69818880/6f63745e-8a23-4d73-8f12-d75850d5cc99)

Al filtrar ese evento con los siguientes parámetros, este no se muestra (Empieza el 30-11 y se filtra a partir del 30-11):
![image](https://github.com/EmoMeza/proyecto-informatico/assets/69818880/bd3b9286-3171-43b3-a7ce-f50f9a106106)

Se probó en un emulador android.

**Comment by carlops22** [comment]
Comprendo, enseguida lo resuelvo

**Comment by carlops22** [comment]
Bug fixeado, ahora filtra correctamente cuando las fechas son las mismas. Cualquier error nuevo no dudes en reabrir el issue ^^
