### ISSUE TITLE
Cambiar respuesta de endpoint

### ISSUE THREAD

**Issue by mvillarios** [EmoMeza/proyecto-informatico#5]
- [x] Funciones GET den como respuesta solo el valor pedido. (O valores pedidos)
- [ ] Todas las funciones retornen algo manejable en caso de error o éxito (JSON, código estado HTTP, etc).

**Comment by EmoMeza** [comment]
@mvillarios en caso de error dudo que se entregue algo manejable (? a que te refieres. como esta ahora si hay un error dice que hay error nomas

**Comment by mvillarios** [comment]
@EmoMeza Que por ejemplo en caso de que un id no exista te manda un código 200 con el mensaje "El id 123 no existe", pero si se inserta algo correctamente te manda el mismo código 200 con un mensaje "se ha insertado correctamente". Entonces si alguien quiere saber desde el front si el id existe o no tiene que revisar el mensaje que manda la petición. Por eso estaba pensando que quizás puedas comunicar con códigos para un manejo mas fácil. Igual estaba pensando que yo podría desde la conexión manejar los mensajes para que sea mas fácil en el front controlar las peticiones.

**Comment by EmoMeza** [comment]
@mvillarios Ahhh yaya te cacho, para cuando lo necesitas? te molesta si lo hago el viernes?

**Comment by mvillarios** [comment]
Cuando puedas nomas

**Comment by EmoMeza** [comment]
@mvillarios creo que ahi esta, revisa si es como te sirve, en teoria en caso de error se envía correctamente, pero en caso de no ser así dimelo

**Comment by mvillarios** [comment]
Ya mira, modifique el código de api_services.dart para dar respuesta según como esta la api, así que ahora no es necesario modificarlo.
