### ISSUE TITLE
Conexion entre eventos y su creador

### ISSUE THREAD

**Issue by mvillarios** [EmoMeza/proyecto-informatico#9]
Habíamos pensado en que como los alumnos van a crear solo eventos vistos por ellos mismos y los CAA van crear solo actividades, dejar el id_caa como id_creador y que al crearlo, si lo crea un alumno darle la matrícula, y si lo crea un CAA darle el id de este.

- [x] Editar id_caa en Evento por id_creador.

Además lo que se había conversado,
- [x] Cambiar booleano visibilidad por global.

**Comment by EmoMeza** [comment]
Acabo de pushear. lo que hice fue:

1. Edité el add/alumno, para que al momento de crearse creara una lista vacia llamada mis_eventos.
2. Edité el seteo de variable visible a global en add/asistencia
3. Arreglé un problema que se generaba por la forma en la que el José habia puesto lo de las fechas.
4. Actualicé el add/evento , de tal forma que al crear un evento se entrega ahora un parametro llamado id_creador, donde o se pone una matricula o se pone un id_objeto de un centro de alumno. Con esto, la funcion revisa el largo del id_creador si es menor que 24 se asume que es matricula y si en cualquier otro caso se asume que es caa (esto porque los id_objeto que son los que utilizamos para los caa, tienen un largo de 24). En caso de ser matricula, guarda dentro de ese alumno el id de el evento en su lista de mis_eventos. Caso contrario solamente lo crea el caa.

Mis dudas son las siguientes:

1. Quieren que el caa tambien tenga su lista de "mis eventos"? 
2. Como quieren que la variable global se inicialice para cuando es creado por un caa y para cuando es creado por un alumno?
3. Como esta el codigo de asistencia actualmente cuando se llega a 5 asistencias la variable global se pone en true. Como eso ya no existirá deberia de borrarlo, espero confirmacion para hacer eso.

Si bien testee rapidamente y me funcionó bien, los invito a probar que los enpoints cambiados funcionen correctamente, tomar en cuenta que hay que probar con un alumno nuevo que tenga creada esa lista vacia llamada mis_eventos.

Saludos!

**Comment by dimaldonado** [comment]
Respuestas a dudas:
1. Como ahora tenemos id_creador, podemos utilizar el endpoint get filter eventos para obtener todos los eventos que haya creado tanto un caa como un alumno utilizando su matrícula o id_caa como filtro, por lo que no es necesario.
2. En el front, una de las cosas que hay que agregar al crear un evento por parte de un centro de alumnos, es una opción que diga si el evento que se está creando será global o de carrera. Por lo que debería estar definido al momento de crearlo. De igual manera, sugeriría que por defecto se establezca en false.
3. Si, eso ya no será necesario, puedes borrarlo.

**Comment by dimaldonado** [comment]
También necesitaremos otra lista más dentro de alumno, esta la utilizaremos para almacenar los id de los eventos a los que el alumno confirme su asistencia.

**Comment by EmoMeza** [comment]
En ese caso sería:

- [ ] Que cuando un centro de alumno cree un evento la variable global sea lo que indiquen. En caso de no especificar, se seteará en False.
- [ ] Borrar el cambio de variable true de global.
- [ ] Añadir otra lista vacia en alumno mi_asistencia (nombre tentativo), la cual cuando un alumno diga que asistirá, añadir el id del evento al cual asistirá

Empezaré a trabajar con esos cambios, igualmente les pido @dimaldonado @mvillarios  que revisen si eso es lo que quieren. 

Saludos!

**Comment by dimaldonado** [comment]
Si, eso es lo que queremos.👍🏻

**Comment by EmoMeza** [comment]
Respecto a este punto: 

>  Que cuando un centro de alumno cree un evento la variable global sea lo que indiquen. En caso de no especificar, se seteará en False.

Cuando un alumno crea un evento este siempre tendrá la variable global en false, mientras para los caa, dentro del body que se entrega en formato json al enpoint se puede especificar si se quiere que sea global o no.

El resto de puntos estan cambiados en la siguiente [branch ](https://github.com/emomeza/proyecto-informatico/tree/9-conexion-entre-eventos-y-su-creador)

No tengo tiempo ahora mismo para realizar tests asi que si pudieran comprobar su funcionamiento agradeceria bastante.

Cualquier duda o problema me dicen, saludos!

**Comment by dimaldonado** [comment]
- [ ] Solucionar problema al agregar un nuevo alumno. Al hacer el post del nuevo alumno, se obtiene el mensaje "se ha insertado correctamente", sin embargo, al hacer un get del alumno utilizando la misma matricula que se utilizó para crearlo, se obtiene el mensaje “el id indefined no existe en la base datos”.

- [ ] Añadir (si es que aún no está) un endpoint que permita obtener la lista mi_asistencia que está dentro de alumno.

**Comment by EmoMeza** [comment]
Hola! El primer punto aun esta en proceso, respecto al segundo, basta con hacer el get del alumno una vez esté arreglado para obtener toda la información del mismo, incluido mi_asistencia.

Comentaré de nuevo cuando haya solucionado el problema, saludos!

**Comment by EmoMeza** [comment]
Hola @dimaldonado !, 

Sabes que acabo de liberarme para hacer lo que me pediste de agregar alumno y que el get no funciona segun tu, y resulta que acabo de revisar y no tiene ningun problema, ni si quiera movi algo y me funcionaba. 

A la proxima revisa bien, probablemente tenga que ver con un error en tu forma de llamar el get. 

De igual forma podemos coordinar si quieres para confirmar que efectivamente esta bien.

Saludos!

**Comment by dimaldonado** [comment]
Tienes razón, por alguna razón ahora funciona bien, pero ahora, obtengo el mismo problema que obtenia haciendo el get, pero esta vez, al momento de hacer el delete de un alumno.

A continuación, te dejo una secuencia con imágenes del proceso, si ves el error que estoy cometiendo, házmelo saber.

1. Creacion de usuario
![image](https://github.com/EmoMeza/proyecto-informatico/assets/102496218/43662a2e-1d01-495d-a434-f4eebcdba37f)

2. Get del usuario
![image](https://github.com/EmoMeza/proyecto-informatico/assets/102496218/d88e2afb-c64f-41cc-badb-f066bca332f4)

3. Delete del usuario

![image](https://github.com/EmoMeza/proyecto-informatico/assets/102496218/0ac09698-5764-4b04-a0ae-3e8dc2fefa4d)

**Comment by EmoMeza** [comment]
Comiteado, deberia estar funcionando, ese error provenía del cambio de matricula de string a entero que no estaba actualizado en las funciones update/delete. Ahora esta funcionando

**Comment by dimaldonado** [comment]
Un error parecido sucede en al momento de usar add/asistencia, como se puede apreciar en la siguiente secuencia:

1.	Verificamos que la matricula tenga un usuario asignado.
![image](https://github.com/EmoMeza/proyecto-informatico/assets/102496218/8c98b3d9-3613-4063-b280-b855e56d9a1f)

2.	Utilizamos la función add/asistencia utilizando la matricula anterior y el id de un evento.
![image](https://github.com/EmoMeza/proyecto-informatico/assets/102496218/4f656308-b7f2-44b3-8a91-03f16d569a53)


Cualquier cambio que se realice, hacerlo en la branch Main-v2-ahora-es-personal.

Gracias de antemano.

**Comment by EmoMeza** [comment]
Buenas @dimaldonado ,

Acabo de arreglar todos los errores presentados con las matriculas. Éstas ya no deberian de causar problemas. 

Debido a que los cambios anteriores a estos fueron realizados en la branch main, para evitar conflictos con merge a la branch principal, te invito a realizar el merge para que en tu branch "Main-v2-ahora-es-personal" se encuentren los cambios realizados.

Saludos!

**Comment by EmoMeza** [comment]
Hola!,

como el problema del titulo del issue parece haberse resuelto con los cambios, procederé a cerrar el issue. Ante cualquier problema aparte de este tema que surga basta con crear otro issue. 

Saludos!
